### ISSUE TITLE
Mettre le date_default_timezone_set dans un autre fichier ?

### ISSUE THREAD

**Issue by Julien-Broyard** [Afpa-repo/CDA-19224-1#16]
Qu'est-ce que vous pensez de mettre le date_default_timezone_set dans un autre fichier ?

```php
namespace App\Entity;

use DateTime;
use DateTimeInterface;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as Assert;

date_default_timezone_set('Europe/Paris');
```
J'avais pensé de le mettre dans le index.php au moins on l'écris une fois et c'est valable pour toute l'application

**Comment by arnaud567** [comment]
ouais bonne idée.
