### ISSUE TITLE
[PROPOSITION] Ajouter des flash messages

### ISSUE THREAD

**Issue by Julien-Broyard** [Afpa-repo/CDA-19224-1#33]
Ça pourrait être sympa d'utiliser des flash messages pour pouvoir facilement prévenir l'utilisateur.
Ex: L'utilisateur viens de créer son compte sans problème et est redirigé. Mais il ne sais pas qu'il doit valider son email ! C'est dans de ce genre de situations que les flashs peuvent être super sympa !

[Documentation](https://symfony.com/doc/current/controller.html#flash-messages) !

**Comment by CocoCouq** [comment]
Je suis justement entrain de les ajouter sur toute la partie login. Je fais en même temps le mot de passe oublié (presque fini).

**Comment by Julien-Broyard** [comment]
Ah bah c'est parfait :tada:
