### ISSUE TITLE
[CHANGEMENT] Utiliser Inky

### ISSUE THREAD

**Issue by Julien-Broyard** [Afpa-repo/CDA-19224-1#34]
Actuellement on utilise Inky pour les email néanmoins on a pris les template "compilé" ducoup il faudrait prendre les version plus courtes pour redonner de l'intêret à Inky !

C'est [ici](https://get.foundation/emails/email-templates.html) que ça se passe !

**Comment by CocoCouq** [comment]
Je vais faire en sorte que ça soit en place avant ce soir ! 👍

**Comment by Julien-Broyard** [comment]
Pas de soucis je fais une petite pause sur le fil rouge mais si tu as besoin d'aide n'hésite pas surtout :+1:

**Comment by CocoCouq** [comment]
C'est bon les mails sont avec inky, tout est ok. Je laisserais Valentin regarder si il veut pour ajouter du design mais j'ai repris la ressource que tu as donné, Julien. Un peu de commentaires et de vérifier du code et je commit.
