### ISSUE TITLE
[BUG] Soucis de CSS/JS sur les formulaires

### ISSUE THREAD

**Issue by Julien-Broyard** [Afpa-repo/CDA-19224-1#36]
Sur les formulaires d'inscription et de connexion il y a des affichages étranges. 
Je verrai sûrement pour travailler dessus demain.

**Comment by CocoCouq** [comment]
J'ai vu, mais j'avoue que j'ai pas chercher d'où ça venait.. Surement un conflit avec le css

**Comment by Julien-Broyard** [comment]
Faudrait voir aussi avec @Isco80 il pourrait peut-être nous aider là dessus ! Mais de toute façon j'ai amélioré le workflow Webpack donc maintenant quand on fera le build dev on aura des sourcemaps. Ce sont des fichiers qui permettent plus facilement le débuggage quand on utilise des outils comme Babel, Webpack et tout ce qui implique du module bundling.
