### ISSUE TITLE
[QUESTION] Précisions sur les entités User|Particular|Professional

### ISSUE THREAD

**Issue by Julien-Broyard** [Afpa-repo/CDA-19224-1#39]
Actuellement je travaille sur les entités que je peaufine tandis que je réflechis à un moyen de lier les entités entre elles.

Ducoup je pense qu'il sera nécessaire de faire un join entre: 
User > Particular
User > Professional

Pour pouvoir utiliser les champs du User dans celles-ci. 
Je pense surtout à la clé du User mais ça pourrait être pour tout les autre champs.

Est-ce qu'un utilisateur deviens particulier par défaut ?
Si oui comment fait-on ? (Au pire on peut créer le particular après avoir créer le user)

Doit-on créer deux formulaire d'inscriptions (ou bien le modifier pour pouvoir choisir particulier ou professionel) ?

**Comment by CocoCouq** [comment]
**Au niveau de l'utilisateur**
J'imagine deux formulaires d'inscription, en avant on favorise l'accès à un compte particulier (C'est l'inscription actuelle), il faudra donc y ajouter les champs de la table particuliers.
Je pense qu'on peut faire un formulaire d'inscription professionnel avec un accès plus discret mais pas non plus caché, par exemple dans le footer (Ce qui le rendrait visible sur toutes les pages).

**Au niveau des tables**
Je pense donc q'il faut bien deux join : 
- User > Particular
- User > Professional

Je ne pense pas que ça soit gênant, il faudra bien penser à faire un transaction à l'insertion 

### Mon avis
On ferais bien de faire 2 formulaires

_Je pense par contre, qu'on est pas obligé de garder le boolean pour particulier mais on peut le garder pour professionnels puisqu'il faudra les vérifier_

**Comment by arnaud567** [comment]
ça me va

**Comment by Julien-Broyard** [comment]
Je m'occupe de faire les joins

**Comment by Julien-Broyard** [comment]
J'ai fais les Joins. J'ai essayé tant bien que mal de faire des relations One to One mais j'ai pas réussi à retirer l'erreur qui dis que le user doit être unique. 

De ce fait j'ai fais une relation Many To One
Si vous avez d'autre proposition n'hésitez pas
Voir #49
