### ISSUE TITLE
Gros Probleme de rigueur en front ! 

### ISSUE THREAD

**Issue by CocoCouq** [Afpa-repo/CDA-19224-1#66]
## À LIRE (Surtout @Isco80)
_Hier j'ai repris l'intégralité du travail réalisé pour pouvoir intégrer le travail de Valentin et corriger les bugs causés par son merge._

### Globalement 
Majoritairement, j'ai vu du bon boulot sauf en regardant le travail de Valentin, je vous avoue que j'ai envie de pleurer.

_Je vais vous expliquez en détail ce que j'ai vu et pourquoi j'ai pris l'initiative de supprimer une bonne partie de ce travail.
(Sans rien changer à l'esthétique...)_ 
**Je vous invite tous à regarder ce qui suit :**

___
### PREMIEREMENT
- Il faut **beaucoup** plus utiliser materialize, on ne peux pas avoir des pages entière sans **aucune** utilisation du framework.
(_Après avoir tout repris, je me dis même que certains ne chargent pas materialize quand ils testent, voir qu'ils ne bossent pas sur le projet !!_)
___
___
### BASE TWIG ET INDEX
On va commencer par le debut ! J'ai repris le code css de la base et de l'index, simplement pour réorganiser.

J'ai donc voulu nettoyer le code de son superflux et là, mon étonnement a été immense. Je n'étais même pas encore arrivé à la premiere categorie sur l'index (les baguettes) - j'avais seulement fini de reprendre jusqu'aux maisons Poudlard - que j'avais déjà **supprimé plus de 100 lignes de css sans rien changer au visuel** !!

##### Je vais donner des exemples :
- J'ai retiré des classes entières sans rien changer au visuel. Sur les 400 premières lignes de base.css j'ai retiré plus de 100 lignes de code **completement** unitil. 
- Quel est l'intéret de mettre un `width: 100%` sur la navbar alors que materialize le fais déjà ? J'en ai retiré plus de 20 !
- J'ai retiré des margin et des padding qui n'influencer pas une seconde le visuel.
- Les images ne sont pas responsives alors qu'il y a une classe `responsive-img`.
- Tu as 40 scale 1.1, tu peux pas faire une classe scale10
- Il n'y avait pas un seul id qui est utilisé sur l'intégralité du css.
- Aucune classe qui en est vraiment une, juste sur les maisons Poudlard, j'ai retiré 20 lignes de ton css en mettant une classe pour ce qui est commain et un id pour le background qui est le **seul** truc différent.
- Est-ce qu'on parle des balises html pas fermées ?!

Je retire d'une seule et même classe :
``` 
display: flex;
flex-direction: column;
min-height: 850px;
margin-right: auto;
margin-left: auto;
```
SANS RIEN CHANGER AU VISUEL !!! Et ce n'est qu'un exemple parmis cent.

Après avoir nettoyé le code css de l'index, j'ai commenté le fichier media queries et là, je vous le donne en mille, tout était responsif. **Les media queries c'est pas de la "bidouille" pour corriger un css hasardeux.**

Et puis c'est comme ça qu'on fait un **simple lien** vers une autre page :
`<button type="button" onclick="window.location.href = '{{ path('productChopsticks') }}'">DÉCOUVRIR NOS BAGUETTES</button>`

Pour la page login, c'est la même histoire, je vous invite à regarder les changements..
___
___
### LA PAGE DES PRODUITS

Venons en à la page des produits !! Franchement c'est quoi ça ?!! 

Déjà tu prends la page de test qu'à crée Arnaud et son controller pour essayer son panier..

Passe encore, mais le pire c'est que tu le rends **non-fonctionnel**. 

#### Prenons le controller
Déjà, tu utilises une fonction que j'ai crée dans ProductRepository sans l'appeler par le bon nom ni avec le bon type !!!
Ça peut pas marcher !!! Tu testes pas ?! 

Tu crées 5 fonctions identiques qui renvoient la même chose :

 La list des produits qui ne marche donc pas et une chaine de caractère qui correspond à la catégorie. On ne va pas créer une route, une fonction pour toutes les catégories en les rentrant à la main !!  
 Tu connais pas la method get ?!
 Il y a 12000 templates de créer qui récupèrent toutes les infos via 12000 controller et là il y a rien qui fonctionne.

#### La partie html.twig
La page html des produits c'est quoi ?! 

**5 COPIER/COLLER avec 5 if pour lire la chaine de caractère de ton controller**
En gros 5 fonctions qui ne marchent pas, 5 * 10 lignes de html et 5 * 2 ligens de javascript pour changer 1 image et le nom de la categorie ?! 

A tout ça, on ajoute 10 ligne de html dans une boucle for qu'Arnaud avait laissé là mais et que tu rends infonctionnel. Faut faire des dump() !
Même le bouton qu'Arnaud avait mit pour ajouter au panier à disparu (forcement y a pas d'interret quand on fait une maquette).
Tu n'importais même pas ton css...

## Parce que 5 jours pour une page comme ça, c'est honteux !

Alors, je ne vois que 2 ppossibilités, soit c'est du code réchauffé d'un autre projet que tu as voulu bidouillé, soit tu tes jamais connecté au projet et tu codes sur une page extérieur en faisant juste html et css.
Il n'y a aucune interaction avec la base de donnée, rien, pas une ligne de back !! 
On dirait que matérialize n'est pas là chez toi !! Tu testes sans ou quoi ?!

Enfin, j'ai tout corrigé et je t'invite à regarder @Isco80 !! Et je t'invite aussi à **refaire l'accueil** de manière dynamique avec la base de donnée ! Avec du materialize un minimum ! Et pas de css qui ne sert à rien !! 

___
Quand on te demande si tu as compris dis "NON" si tu n'as pas compris !! Si tu n'arrives pas à te connecter au projet dis le !!! 
On te dis assez qu'on peut t'aider alors quand je vois un boulot comme ça, j'ai l'impression que c'est du foutage de gueule.
Julien a créé pleins d'outils pour rendre le projet accessible, il n'y a qu'à demander !!

**On en reparlera au prochain vocal, tu peux déjà pull le projet et commencer à bosser sur l'index en ouvrant la doc materialize et après un** `bin/chaudron start`

**Comment by Isco80** [comment]
Écoute Corentin je te cache pas que je suis très surpris de ton message.

Effectivement au niveau du Css j'aurais pu revoir certaines choses et ajuster mon code.
Je travaille avec des classes et pas des ids avec Css.
Par contre j'avais signalé vendredi que sur mon code Css plusieurs de mes classes ne sont dupliqués sans aucune raison depuis mon premier merge.

Pour le fichier MediaQuery je suis obligé de rendre les choses responsives moi-même car j'utilise pas Materialize.

Concernant la page produite j'ai utilisé la base de données pour afficher les produits selon leur catégorie, cela fonctionnait parfaitement de mon côté, sinon je n'aurai clairement pas commit mon boulot et j'aurai demandé de l'aide. J'ai codé à partir de la page qu'Arnaud avait créée pensent que c'était la bonne car pour moi c'était logique de reprendre son boulot pour l'ajuster à son panier sur lequel il travaillait.

Mon objectif de la semaine était de faire la page produite et la page détail des produits (que j'allais faire demain). Donc mon objectif allait être rempli.

En aucun cas j'aurai repris mon boulot d'un autre projet où travaillais sur des pages extérieurs au projet. Je pull chaque fois le projet et je travaille dessus.

Ça me blesse car j'ai l'impression de passer pour une mauvaise personne.

Concernant la suite pas de soucis j'utiliserais seulement Materialize pour le design car ma façon de procéder ne convient pas. Pour le reste on en discute en vocal.

En espèrent repartir sur de bonnes bases.
