### ISSUE TITLE
Pourquoi il y a deux ID et un join qui mène sur la même table ?

### ISSUE THREAD

**Issue by Julien-Broyard** [Afpa-repo/CDA-19224-1#8]
Pourquoi il y a deux ID et un join qui mène sur la même table ?

$id et $idCategory

```php
class Ct404Category
{
    /**
     * @var int
     * @ORM\Column(name="id", type="integer", nullable=false)
     * @ORM\Id
     * @ORM\GeneratedValue(strategy="IDENTITY")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=50)
     */
    private $categoryName;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\Ct404Category")
     * @ORM\JoinColumn(nullable=true)
     */
    private $idCategory;
```

**Comment by arnaud567** [comment]
En gros à la base Gaëtan voulait qu'une catégorie puisse appartenir à une autre catégorie, d'où le join sur la même table, si je me souviens bien Cédric avait montré ça dans la partie sql, après si qqun a une autre idée qui vaut le coup je suis preneur.

**Comment by Julien-Broyard** [comment]
Pas de soucis je pense avoir trouvé un truc pour faire ça en Symfony !
